export * from './Login/Login'
export * from './Register/Register'
export * from './Dashboard/Dashboard'
export * from './Reset/Reset'
export * from './Profile/Profile'
export * from './Header/Header'
export * from './NotFound/NotFound'